# Request
sensor_msgs/Image image
string[] dictionaries
float64[] marker_sizes
sensor_msgs/CameraInfo camera_info
---
# Response
sensor_msgs/Image visualization_2d
sensor_msgs/Image visualization_3d
aruco_msgs/MarkerArray markers
